### ISSUE TITLE
why no sparky creddit !!!

### ISSUE THREAD

**Issue by S4ltster** [VilariStorms/Cumsay-Gooey#1]
why u steely auto mobelie codey from my reputation @Glass-Paramedic @Glass-Paramedic

**Comment by Glass-Paramedic** [comment]
You are  credited in the source code!!!

**Comment by Deltara3** [comment]
@VilariStorms cvan you bleive

**Comment by VilariStorms** [comment]
SHOKING

**Comment by Deltara3** [comment]
#1

**Comment by S4ltster** [comment]
> 

![image](https://user-images.githubusercontent.com/87864112/236362239-f01b8775-c018-41e3-9992-2681d590a197.png)

**Comment by S4ltster** [comment]
> You are credited in the source code!!!

![image](https://user-images.githubusercontent.com/87864112/236362272-a4b8be82-49fb-4b15-9e39-de3fdcc8f580.png)

**Comment by Deltara3** [comment]
You are credited in the source code!!!
